# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 每天10:30执行

name: Bili Task

on:
   push:
     branches: main
     paths:
     - 'bili/bilitask'
     - '.github/workflows/BiliTask.yml'
   gollum:
   workflow_dispatch:
   schedule:
       - cron: '30 2 * * *'

env:
  SAVE_DIR_NAME: 'BilibiliTask'

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Clone BilibiliTask
      run: |
        git clone https://github.com/srcrs/BilibiliTask.git $SAVE_DIR_NAME
        WORK_DIR=$GITHUB_WORKSPACE/$SAVE_DIR_NAME && echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      env:
        BILI_JCT: ${{ secrets.BILITASK_BILI_JCT }}
        DEDEUSERID: ${{ secrets.BILITASK_DEDEUSERID }}
        SESSDATA: ${{ secrets.BILITASK_SESSDATA }}
        SCKEY: ${{ secrets.SERVERCHAN_KEY }}
        DINGTALK: ${{ secrets.DINGTALK }}
        PUSHPLUSTK: ${{ secrets.PUSHPLUSTK }}
        SENDKEY: ${{ secrets.SENDKEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: cd $WORK_DIR && sh $WORK_DIR/gradlew runMain
