# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 每天10:30执行

name: BiliTask

on:
   push:
     branches: main
     paths:
     - 'task/bilitask'
     - '.github/workflows/BiliTask.yml'
   gollum:
   workflow_dispatch:
   schedule:
       - cron: '30 2 * * *'

env:
  SAVE_DIR_NAME: 'BilibiliTask'
  GIT_REPO_URL: 'https://github.com/srcrs/BilibiliTask.git'
  # 本仓库 commit message
  COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
  # github api 请求头的 accept
  GIT_API_ACCEPT: 'application/vnd.github.v3+json'
  # github api token
  GIT_API_TOKEN: ${{ github.token }}
  # github api 请求头的验证 token
  GIT_API_AUTH: 'token ${{ github.token }}'
  # 获取所有 workflows API 地址 ${{ github.repository }} 和 $GITHUB_REPOSITORY 相同
  GIT_API_RUNS_LIST: 'https://api.github.com/repos/${{ github.repository }}/actions/runs'
  deleteOldRunsUrl: 'https://github.com/inused/actionTest/raw/main/tool/deleteOldRuns.py'

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Clone BilibiliTask
      run: |
        git clone $GIT_REPO_URL $SAVE_DIR_NAME
        WORK_DIR=$GITHUB_WORKSPACE/$SAVE_DIR_NAME && echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV
        echo "GITHUB_WORKSPACE=$WORK_DIR" >> $GITHUB_ENV
        confPath=$WORK_DIR/src/main/resources/config.yml
        # 修改每日投币数
        sed -i 's/coin:.*/coin: 0/g' $confPath
        echo '------当前配置信息如下:' && cat $confPath

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      env:
        BILI_JCT: ${{ secrets.BILITASK_BILI_JCT }}
        DEDEUSERID: ${{ secrets.BILITASK_DEDEUSERID }}
        SESSDATA: ${{ secrets.BILITASK_SESSDATA }}
        SCKEY: ${{ secrets.SERVERCHAN_KEY }}
        DINGTALK: ${{ secrets.DINGTALK }}
        PUSHPLUSTK: ${{ secrets.PUSHPLUSTK }}
        SENDKEY: ${{ secrets.SENDKEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        cd $WORK_DIR
        # 随机延时 30~60 分钟
        sleepSeconds=$((RANDOM % 1800 + 1800)) && doTime=`date -d "+$sleepSeconds second" "+%Y-%m-%d %H:%M:%S"`
        # 只有定时任务触发的才需要延时
        [[ "$GITHUB_EVENT_NAME" == "schedule" ]] && echo "等待 $sleepSeconds 秒后的 $doTime 开始执行" && sleep "$sleepSeconds"s
        # push commit信息中不是以 skip 开头的才执行，以skip开头的直接取消
        [[ $COMMIT_MESSAGE == skip* ]] && curl -s -H "Authorization: $GIT_API_AUTH" -H "Accept: $GIT_API_ACCEPT" -X POST "$GIT_API_RUNS_LIST/$GITHUB_RUN_ID/cancel" || sh $WORK_DIR/gradlew runMain

    - name: Delete Cancelled And Old Runs
      env:
        recordSavedNum: 5
      run: wget $deleteOldRunsUrl -q -O deleteOldRuns.py && python3 deleteOldRuns.py

