name: TEST

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yml'
  #schedule:
  #  - cron: '*/1 * * * *'

env:
  # LSP giturl
  LSP_GIT_URL: 'https://github.com/LSPosed/LSPosed.git'
  # 管理器actions地址
  MANAGER_CI_URL: 'https://github.com/LSPosed/LSPosed/actions?query=workflow%3AManager'
  # 老包名
  MANAGER_PACKAGE_NAME_OLD: 'io.github.lsposed.manager'
  # 新包名
  MANAGER_PACKAGE_NAME_NEW: 'me.lspmanager'
  # github api 请求头的 accept
  GIT_API_ACCEPT: 'application/vnd.github.v3+json'
  # 获取所有 workflows API 地址
  GIT_API_RUNS_LIST: 'https://api.github.com/repos/${{ github.repository }}/actions/runs'
  # lsp 的API地址
  GIT_API_RUNS_LIST_LSP: 'https://api.github.com/repos/LSPosed/LSPosed/actions/runs'
  # 代码保存位置
  WORK_DIR_NAME: 'LSPosed'
  GIT_API_AUTHO: 'token ${{ github.token }}'

jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{ startsWith(github.event.head_commit.message, 'lspmanager') }}
    outputs:
      buileOutput: ${{ steps.test1.output.aaa }}
    steps:
      - name: Get Latest CI Info
        run: echo "111" >> 1.txt
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: 1.txt
      - name: test1
        id: test1
        run: |
          echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
          echo '----------------------------------------------------------------------------------------------------'
          echo "::set-output name=aaa::aaa.buileOutput.value"
  
  testJob:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      aaa: ${{ needs.build.outputs.buileOutput }}
    steps:
      - name: test
        run: |
          echo $aaa
      - name: test2
        run: |
          echo $aaa
          
          
